packages:
  - demo
  - resonare

allowBuilds:
  esbuild: false
  sharp: false
  workerd: true

minimumReleaseAge: 10080 # 7 days
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeStrict: true

blockExoticSubdeps: true
savePrefix: ''

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200 # 30 days
